CREATE TABLE `sql`.logs(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    package VARCHAR(64) NOT NULL,
    stage VARCHAR(32) NULL,
    log MEDIUMTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `sql`.history(
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    runner VARCHAR(64) NOT NULL,
    packages TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);