

  - name: 'coreutils'
    subdir: 'ports'
    version: '9.5'

    url: 'https://repo.hades-os.org/sources/coreutils-v9.5.tar.xz'
    format: 'tar.xz'
    extract-path: 'coreutils-v5.2'
    extract-strip: 1
