sources:
  - name: binutils
    subdir: 'ports'
    version: '2.43'

    url: 'https://repo.hades-os.org/sources/binutils-v2.43.tar.xz'
    format: 'tar.xz'
    extract-path: 'binutils-v2.43'
    extract-strip: 1

  - name: gcc
    subdir: 'ports'
    version: '13.2.0'

    url: 'https://repo.hades-os.org/sources/gcc-v13.2.0.tar.xz'
    format: 'tar.xz'
    extract-strip: 1
    extract-path: 'gcc-v13.2.0'

    tools-required:
      - host-autoconf
      - host-automake
    regenerate:
      # download_prerequisites should probably move to some "post_checkout" step.
      - args: ['./contrib/download_prerequisites']
        workdir: '@THIS_SOURCE_DIR@'
      - args: ['autoconf']
        workdir: '@THIS_SOURCE_DIR@/gcc'
      - args: ['autoconf']
        workdir: '@THIS_SOURCE_DIR@/libstdc++-v3'

  - name: mlibc
    subdir: 'ports'
    version: '5.0'

    url: 'https://repo.hades-os.org/sources/mlibc-v5.0.tar.xz'
    format: 'tar.xz'
    extract-path: 'mlibc-v5.0'
    extract-strip: 1

  - name: autoconf
    subdir: 'ports'
    version: '2.69'

    url: 'https://repo.hades-os.org/sources/autoconf-v2.69.tar.xz'
    format: 'tar.xz'
    extract-path: 'autoconf-v2.69'
    extract-strip: 1

  - name: automake
    subdir: 'ports'
    version: '1.16'

    url: 'https://repo.hades-os.org/sources/automake-v1.16.tar.xz'
    format: 'tar.xz'
    extract-path: 'automake-v1.16'
    extract-strip: 1

  - name: libtool
    subdir: 'ports'
    version: '2.4.6'

    url: 'https://repo.hades-os.org/sources/libtool-v2.4.6.tar.xz'
    format: 'tar.xz'
    extract-path: 'libtool-v2.4.6'
    extract-strip: 1

  - name: 'pkg-config'
    subdir: 'ports'
    version: '0.29.2'

    url: 'https://repo.hades-os.org/sources/pkg-config-v0.29.2.tar.xz'
    format: 'tar.xz'
    extract-path: 'pkg-config-v0.29.2'
    extract-strip: 1

  - name: 'bash'
    subdir: 'ports'
    version: '5.2'

    url: 'https://repo.hades-os.org/sources/bash-v5.2.tar.xz'
    format: 'tar.xz'
    extract-path: 'bash-v5.2'
    extract-strip: 1