

  - name: 'coreutils'
    subdir: 'ports'
    version: '9.5'

    url: 'https://repo.hades-os.org/sources/coreutils-v9.5.tar.xz'
    format: 'tar.xz'
    extract-path: 'coreutils-v5.2'
    extract-strip: 1

  - name: 'zlib'
    subdir: 'ports'
    version: '1.2.12'

    url: 'https://repo.hades-os.org/sources/zlib-v1.2.12.tar.xz'
    format: 'tar.xz'
    extract-path: 'zlib-v1.2.12'
    extract-strip: 1

  - name: 'xz-utils'
    subdir: 'ports'
    version: '5.4.4'

    url: 'https://repo.hades-os.org/sources/xz-utils-v5.4.4.tar.xz'
    format: 'tar.xz'
    extract-path: 'xz-utils-5.4.4'
    extract-strip: 1

  - name: 'openssl'
    subdir: 'ports'
    version: '1.1.1'

    url: 'https://repo.hades-os.org/sources/openssl-v1.1.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'openssl-v1.1.1'
    extract-strip: 1

  - name: 'libmd'
    subdir: 'ports'
    version: '1.1.0'

    url: 'https://repo.hades-os.org/sources/libmd-v1.1.0.tar.xz'
    format: 'tar.xz'
    extract-path: 'libmd-v1.1.0'
    extract-strip: 1

  - name: 'dpkg'
    subdir: 'ports'
    version: '1.22.11'

    url: 'https://repo.hades-os.org/sources/dpkg-v1.22.11.tar.xz'
    format: 'tar.xz'
    extract-path: 'dpkg-v1.22.11'
    extract-strip: 1

  - name: 'libxcrypt'
    subdir: 'ports'
    version: '4.4.36'

    url: 'https://repo.hades-os.org/sources/libxcrypt-v4.4.36.tar.xz'
    format: 'tar.xz'
    extract-path: 'libxcrypt-v4.4.36'
    extract-strip: 1

  - name: 'shadow'
    subdir: 'ports'
    version: '4.8.1'

    url: 'https://repo.hades-os.org/sources/shadow-v4.8.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'shadow-v4.8.1'
    extract-strip: 1
