sources:
  - name: binutils
    subdir: 'ports'
    version: '2.43'

    url: 'https://repo.hades-os.org/sources/binutils-v2.43.tar.xz'
    format: 'tar.xz'
    extract-path: 'binutils-v2.43'
    extract-strip: 1

  - name: gcc
    subdir: 'ports'
    version: '13.2.0'

    url: 'https://repo.hades-os.org/sources/gcc-v13.2.0.tar.xz'
    format: 'tar.xz'
    extract-strip: 1
    extract-path: 'gcc-v13.2.0'

    tools-required:
      - host-autoconf
      - host-automake
    regenerate:
      # download_prerequisites should probably move to some "post_checkout" step.
      - args: ['./contrib/download_prerequisites']
        workdir: '@THIS_SOURCE_DIR@'
      - args: ['autoconf']
        workdir: '@THIS_SOURCE_DIR@/gcc'
      - args: ['autoconf']
        workdir: '@THIS_SOURCE_DIR@/libstdc++-v3'

  - name: mlibc
    subdir: 'ports'
    version: '5.0'

    git: 'https://github.com/rozjin/mlibc'
    branch: 'release-5.0'

#    url: 'https://repo.hades-os.org/sources/mlibc-v5.0.tar.xz'
#    format: 'tar.xz'
#    extract-path: 'mlibc-v5.0'
#    extract-strip: 1

  - name: autoconf
    subdir: 'ports'
    version: '2.69'

    url: 'https://repo.hades-os.org/sources/autoconf-v2.69.tar.xz'
    format: 'tar.xz'
    extract-path: 'autoconf-v2.69'
    extract-strip: 1

  - name: automake
    subdir: 'ports'
    version: '1.16'

    url: 'https://repo.hades-os.org/sources/automake-v1.16.tar.xz'
    format: 'tar.xz'
    extract-path: 'automake-v1.16'
    extract-strip: 1

  - name: libtool
    subdir: 'ports'
    version: '2.5.4'

    url: 'https://repo.hades-os.org/sources/libtool-v2.5.4.tar.xz'
    format: 'tar.xz'
    extract-path: 'libtool-v2.5.4'
    extract-strip: 1

  - name: 'pkg-config'
    subdir: 'ports'
    version: '0.29.2'

    url: 'https://repo.hades-os.org/sources/pkg-config-v0.29.2.tar.xz'
    format: 'tar.xz'
    extract-path: 'pkg-config-v0.29.2'
    extract-strip: 1

  - name: 'bash'
    subdir: 'ports'
    version: '5.1'

    url: 'https://repo.hades-os.org/sources/bash-v5.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'bash-v5.1'
    extract-strip: 1

  - name: 'bison'
    subdir: 'ports'
    version: '3.6.2'

    url: 'https://repo.hades-os.org/sources/bison-v3.6.2.tar.xz'
    format: 'tar.xz'
    extract-path: 'bison-v3.6.2'
    extract-strip: 1

  - name: 'coreutils'
    subdir: 'ports'
    version: '9.5'

    url: 'https://repo.hades-os.org/sources/coreutils-v9.5.tar.xz'
    format: 'tar.xz'
    extract-path: 'coreutils-v5.2'
    extract-strip: 1

  - name: 'gettext'
    subdir: 'ports'
    version: '0.22.3'

    url: 'https://repo.hades-os.org/sources/gettext-v0.22.3.tar.xz'
    format: 'tar.xz'
    extract-path: 'gettext-v0.22.3'
    extract-strip: 1

  - name: 'iconv'
    subdir: 'ports'
    version: '1.17'

    url: 'https://repo.hades-os.org/sources/iconv-v1.17.tar.xz'
    format: 'tar.xz'
    extract-path: 'iconv-v1.17'
    extract-strip: 1

  - name: 'ncurses'
    subdir: 'ports'
    version: '6.2'

    url: 'https://repo.hades-os.org/sources/ncurses-v6.2.tar.xz'
    format: 'tar.xz'
    extract-path: 'ncurses-v6.2'
    extract-strip: 1

  - name: 'readline'
    subdir: 'ports'
    version: '8.1'

    url: 'https://repo.hades-os.org/sources/readline-v8.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'readline-v8.1'
    extract-strip: 1

  - name: 'zlib'
    subdir: 'ports'
    version: '1.2.12'

    url: 'https://repo.hades-os.org/sources/zlib-v1.2.12.tar.xz'
    format: 'tar.xz'
    extract-path: 'zlib-v1.2.12'
    extract-strip: 1

  - name: 'xz-utils'
    subdir: 'ports'
    version: '5.4.4'

    url: 'https://repo.hades-os.org/sources/xz-utils-v5.4.4.tar.xz'
    format: 'tar.xz'
    extract-path: 'xz-utils-5.4.4'
    extract-strip: 1

  - name: 'openssl'
    subdir: 'ports'
    version: '1.1.1'

    url: 'https://repo.hades-os.org/sources/openssl-v1.1.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'openssl-v1.1.1'
    extract-strip: 1

  - name: 'libmd'
    subdir: 'ports'
    version: '1.1.0'

    url: 'https://repo.hades-os.org/sources/libmd-v1.1.0.tar.xz'
    format: 'tar.xz'
    extract-path: 'libmd-v1.1.0'
    extract-strip: 1

  - name: 'dpkg'
    subdir: 'ports'
    version: '1.22.11'

    url: 'https://repo.hades-os.org/sources/dpkg-v1.22.11.tar.xz'
    format: 'tar.xz'
    extract-path: 'dpkg-v1.22.11'
    extract-strip: 1

  - name: 'libxcrypt'
    subdir: 'ports'
    version: '4.4.36'

    url: 'https://repo.hades-os.org/sources/libxcrypt-v4.4.36.tar.xz'
    format: 'tar.xz'
    extract-path: 'libxcrypt-v4.4.36'
    extract-strip: 1

  - name: 'shadow'
    subdir: 'ports'
    version: '4.8.1'

    url: 'https://repo.hades-os.org/sources/shadow-v4.8.1.tar.xz'
    format: 'tar.xz'
    extract-path: 'shadow-v4.8.1'
    extract-strip: 1

  - name: 'linux'
    subdir: 'ports'
    version: '6.1.8'

    url: 'https://repo.hades-os.org/sources/linux-v6.1.8.tar.xz'
    format: 'tar.xz'
    extract-path: 'linux-v6.1.8'
    extract-strip: 1

