source:
  name: 'pkg-config'
  subdir: 'ports'
  version: '0.29.2'

  git: 'https://gitlab.freedesktop.org/pkg-config/pkg-config.git'
  tag: 'pkg-config-0.29.2'
  tools-required:
    - host-autoconf
    - host-automake
    - host-libtool
  regenerate:
    - args: ['./autogen.sh']
      environ:
        NOCONFIGURE: 'yes'

tools:
  - name: host-pkg-config
    version: '0.29.2'
    from_source: pkg-config
    configure:
      - args: 
        - '@THIS_SOURCE_DIR@/configure'
        - '--prefix=@PREFIX@'
        - '--host=@TARGET@'
        - '--with-internal-glib'
    compile:
      - args: ['make', '-j@PARALLELISM@']
    install:
      - args: ['make', 'install-strip']
